### ISSUE TITLE
Fails on Node 0.12

### ISSUE THREAD

**Issue by sindresorhus** [bower/buffered-spawn#2]
https://travis-ci.org/bower/buffered-spawn/jobs/49946591

**Comment by sindresorhus** [comment]
@satazor

**Comment by satazor** [comment]
The issue seems to be with https://github.com/IndigoUnited/node-cross-spawn. I've not yet installed nodejs 0.12.

**Comment by satazor** [comment]
Fixed, see: https://github.com/IndigoUnited/node-cross-spawn/commit/451412a4370764ca6446e08c45851b07a423975f

Kind of stupid.. but.. you know.. its nodejs!

**Comment by satazor** [comment]
We should bump `buffered-spawn` version too, so that users download the new `cross-spawn` version.
Can you do it?

**Comment by satazor** [comment]
I just did it, published 1.0.1
 Should be working now.
