### ISSUE TITLE
feature: only log progress from `stderr`

### ISSUE THREAD

**Issue by zaggino** [bower/buffered-spawn#3]
Would it be possible to alter the library, so it can be set up to log progress only from `stderr` and not also from `stdout` ? I have an executable which I'm calling and it logs the correct output to the `stdout` and progress messages to `stderr`. Problem is, this gets mixed together in the `.progress` callback of a promise.

**Comment by satazor** [comment]
What about both get notified but with a type? We would have to modify notify to pass an object with maybe { type: 'stderr|stdout', data: buffer }

**Comment by zaggino** [comment]
Yes, sure, that'd solve the same problem.

**Comment by satazor** [comment]
Can you do PR with this stuff?

**Comment by zaggino** [comment]
Sure, can do that.

**Comment by satazor** [comment]
Thanks
